carikonco/urls.py
from django.urls import path
from . import views

app_name = 'carikonco'

urlpatterns = [
    path('', views.searchKonser, name="mysearchkonser"),
    path('myfindkonco/', views.findKonco, name='myfindkonco'),
    path('myformkonco/', views.formFindKonco, name='myformkonco'),
    path('mydelkonco/<id>/', views.delete_konco, name='mydelkonco'),
]

tk2ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('findKonco/', include('carikonco.urls')),
    path('events/', include('konser.urls')),
    path('tiket/', include('caritiket.urls')),
    path('news/', include('gossip.urls')),
]

users/urls.py
from django.urls import path, re_path
from .views import *

app_name = "users"

urlpatterns = [
    #re_path(r'^login/$', login_view, name="login"),
    re_path(r'^signup/$', signup_view, name = "signup"),
    re_path(r'^profile/$', profile, name="profile")
]

carikonco/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class KoncoKonser(models.Model):
    namalengkap = models.CharField(max_length= 75)
    notelepon = models.CharField(max_length=20)
    namakonser = models.CharField(max_length= 75)
    tempatkonser = models.CharField(max_length= 75)
    tanggalkonser = models.DateField(default = timezone.now)
    pesan = models.CharField(max_length= 255)

    def __str__(self):
        return "{}".format(self.namalengkap)

carikonco/forms.py
from . import models
from django import forms


class FormFindKonser(forms.ModelForm):
    namalengkap = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                "class" : "txt-form form-control",
                "required"  : True,
                "placeholder"   : "Nama Lengkap",
            }
        )
    )
    notelepon = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                "class" : "txt-form form-control",
                "required"  : True,
                "placeholder" : "No telepon",
            }
        )
    )
    namakonser = forms.CharField(
        widget= forms.TextInput(
            attrs = {
                "class" : "pilih-tanggal form-control",
                "required" : True,
                "placeholder" : "Nama Konser",
            }
        )

    )
    tempatkonser = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                "class" : "txt-form form-control",
                "placeholder"  : "Tempat konser",
                "required"  : True,
            }
        )
    )
    tanggalkonser = forms.DateField(
        widget = forms.SelectDateWidget(
            attrs = {
                "class" : "pilih-tanggal form-control ",
                "required"  : True,
            }
        )
    )
    pesan = forms.CharField(
        widget = forms.Textarea(
            attrs = {
                "class" : "txt-form form-control",
                "placeholder" : "Pesan",
                "required"  : True,
                "rows":5, 
                "cols":10,
            }
        )
    )
    class Meta:
        model = models.KoncoKonser
        fields = [
            'namalengkap', 'notelepon', 'namakonser', 'tempatkonser', 'tanggalkonser', 'pesan',
        ]

carikonco/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import KoncoKonser

# Create your views here.
def searchKonser(request):
    return render(request, 'searchKoncoKonser.html')

def findKonco(request):
    return render(request, 'findKonco.html')

def formFindKonco(request):
    form = forms.FormFindKonser()
    if request.method == "POST":
        form = forms.FormFindKonser(request.POST)
        if form.is_valid():
            form.save()
            return redirect('carikonco:myfindkonco')
    return render(request, 'formFindKonco.html', {'form':form})

def findKonco(request):
    daftar_item = KoncoKonser.objects.order_by('tanggalkonser')
    response = {
        'daftar_item' :daftar_item,
    }
    return render(request, 'findKonco.html', response)

def delete_konco(request, id):
    KoncoKonser.objects.get(id = id).delete()
    return redirect('carikonco:myfindkonco')

carikonco/templates/findKonco.html
{% extends "base.html" %}

{% load static %}
{% block title %} Find Konco {% endblock %}

{% block page_content %}
<div class="div-find-konco">
    <h1 class="h-fk">Post a Konco Request Here!</h1>
    <p class="text-fk"> Kamu bisa mencari teman yang ingin datang ke konser yang sama denganmu atau menambahkan dirimu disini</p>
    <a href="{% url 'carikonco:myformkonco' %}"><button id="bt-fk" type="button">Add Me!</button></a>
</div>

<div class="results card konco bg-danger text-white" style="width: 18rem;">
    </div>
    {% for item in daftar_item %}
        <div class="card konco bg-danger text-white " style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ item.namakonser }}</h5>
                <h6 class="card-subtitle mb-3  text-white ">{{ item.tempatkonser }}, {{ item.tanggalkonser }}</h6>
                <p class="card-text">{{ item.pesan }}</p>
                <h6 class="card-subtitle mb-3  text-white">{{ item.namalengkap }}</h6>
                <h6 class="card-subtitle mb-3  text-white">{{ item.notelepon }}</h6>
                <a href="{% url 'carikonco:mydelkonco' id=item.id%}" class="card-link text-white">Delete</a>
            </div>
        </div>
        {% endfor %}

{% endblock %}

carikonco/templates/formFindKonco.html
{% extends "base.html" %}

{% load static %}
{% block title %} Form Find Konco {% endblock %}
{% block page_content %}
<div class="div-find-konco">
  <h1 class="h-fk">Add Yourself Here!</h1>
  <p class="text-fk"> Silahkan lengkapi form berikut ini</p>
</div>
<div class ="outer-form form-column col-4 ">
  <form action="" method="POST" class="all-form">
      {% csrf_token %}
    <div class="form-group ">
        <label>Nama Lengkap</label>
        {{ form.namalengkap}}
    </div>
    <div class="form-group">
       <label>No Telepon</label>
       {{ form.notelepon }}
      
    </div>
    <div class="form-group">
       <label>Nama Konser</label>
        {{ form.namakonser }}
      
    </div>
    <div class="form-group">
       <label>Tempat Konser</label>
        {{ form.tempatkonser }}
      
    </div>
    <label for="InputTempat">Tanggal Konser</label>
    <div class="form-row">
      <div class="col-3.5">
          {{ form.tanggalkonser }}
      </div>
    </div>

    <div class="form-group">
      <label>Pesan</label>
         {{ form.pesan }}
    </div>
    <a href="{% url 'carikonco:myfindkonco' %}"> <button type="button" class="btn btn-primary" id="back">Back</button> </a>
    <button type="submit" class="btn btn-primary btn-am">Add Me!</button>
  </form>
</div>
{% endblock %}

carikonco/templates/searchKoncoKonser.html
{% extends "base.html" %}

{% load static %}
{% block title %} Find Konco {% endblock %}

{% block page_content %}
<div class="div-find-konco">
    <h1 class="h-fk">Find Your Konco Here!</h1>
    <p class="text-fk"> Kamu bisa mencari teman yang ingin datang ke konser yang sama denganmu atau menambahkan dirimu disini</p>
    <input id="search" placeholder="Singer or Concert">
    <button id="button" type="button">Search</button>
</div>
<div class="table-responsive-md" >
    <table class="table table-bordered" id="table-books">
        <thead class="thead-dark">
        <tr>
            <th scope="col">No</th>
            <th scope="col">Concert Name</th>
            <th scope="col">Location</th>
            <th scope="col">Date</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody id="results">
        
        </tbody>
    </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'admin/js/carikonco.js' %}"></script>
{% endblock %}