carikonco/urls.py
from django.urls import path
from . import views

app_name = 'carikonco'

urlpatterns = [
    path('', views.searchKonser, name="mysearchkonser"),
    path('myfindkonco/', views.findKonco, name='myfindkonco'),
    path('myformkonco/', views.formFindKonco, name='myformkonco'),
    path('mydelkonco/<id>/', views.delete_konco, name='mydelkonco'),
]

caritiket/urls.py
from django.urls import path,include

from . import views

app_name = 'caritiket'

urlpatterns = [
   path('viewjualtiket/', views.viewjualtiket, name='viewjualtiket'),
   path('isijualtiket/', views.isijualtiket, name='isijualtiket'),
]

gossip/urls.py
from django.urls import path
from . import views

app_name = 'gossip'

urlpatterns = [
    path('', views.gossip, name='mygossip'),
    path('data/', views.data, name = 'mygossipdata')
]

homepage/urls.py
from django.urls import path

from .views import*

app_name = "homepage"

urlpatterns = [
    path('', Homepage.as_view(), name='Homepage'),
]

konser/urls.py
from django.urls import path
from . import views

app_name = 'konser'

urlpatterns = [
    path('', views.konser, name='mykonser'),
    path('formevents/', views.formkonser, name='myformkonser'),
]

tk2ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('findKonco/', include('carikonco.urls')),
    path('events/', include('konser.urls')),
    path('tiket/', include('caritiket.urls')),
    path('news/', include('gossip.urls')),
]

users/urls.py
from django.urls import path, re_path
from .views import *

app_name = "users"

urlpatterns = [
    #re_path(r'^login/$', login_view, name="login"),
    re_path(r'^signup/$', signup_view, name = "signup"),
    re_path(r'^profile/$', profile, name="profile")
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.views.generic import TemplateView

# Create your views here.
class Homepage(TemplateView):
    template_name = 'homepage.html'

homepage/templates/base.html
{% load static %}
<!DOCTYPE HTML>

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/bootstrap.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Konco Konser</title>
        {% block head_content %}
        
        {% endblock %}

    </head>
<body>
    <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top " >
                    <a class="navbar-brand" href="{% url 'homepage:Homepage' %}">
                            KoncoKonser
                    </a>
                    <!-- Toggler/Collapsible Button -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    {% if user.is_authenticated %}
                    <h4 style="color: white;">Hello {{user.username}}</h4>
                    {% endif %}
                    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                        <ul class="navbar-nav ml-auto " >
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'carikonco:mysearchkonser' %}">Find Your Konco Here!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'konser:mykonser' %}">Events</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'gossip:mygossip' %}">Gossip</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caritiket:viewjualtiket' %}">Tickets</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'users:profile' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link logout" href="{% url 'logout' %}">logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'login' %}">Login</a>
                            </li>
                            {% endif %}
                            </ul> 
                            </div>
        </nav>
    </header>
    {% block page_content %}
    {% endblock %}

    <script>
        $(.)

    </script>
    <footer>
        <div class ="footer-border"  >
            <p class="text-footer"> Made with love from Arkan, Michelle, Rofi, Tesa </p>
        </div>
    </footer>
</body>
</html>

homepage/templates/homepage.html
{% extends "base.html" %}

{% load static %}
{% block head_content %}
<style>
    header {
    margin-bottom: 0px;
}
</style>
{% endblock %}

{% block page_content %}
<div class="top-lp">
    <p class="text-lp">MALAS NONTON KONSER SENDIRIAN?</p>
    <a href="{%url 'carikonco:mysearchkonser' %}"><button class="bt-lp">Find Your Konco Here!</button></a>
</div>
<div class="about-lp">
    <p class="heading-about-lp">ABOUT US</p>
    <p class="text-about-lp"> Kami adalah platform untuk menyatukan pecinta musik dari berbagai golongan dan genre</p>
</div>
{% endblock %}